### ISSUE TITLE
Cannot find module processQueues.js

### ISSUE THREAD

**Issue by twaddlac** [chemgen-ny-ad/chemgen-next#4]
I'm at this step:
```
node jobs/processQueues.js --limit 1 --site AD --search-pattern CHEM

and the error I'm getting is:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/alan/projects/gunsiano/dockers/chemgen-next/chemgen-next-server/jobs/processQueues.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

I don't really know what each one of these steps is doing but my intuition is that this script has been renamed with 'processScreens.js'? I ran it with this and it didn't crash but it also produced the following output:
```
node jobs/processScreens.js --limit 1 --site AD --search-pattern CHEM                   ⏎ master ✱ ◼
NODE_ENV: ? "dev"
CHEMGEN_HOST: ? "localhost"
(node:59402) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:59402) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:59402) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
info:    Queueing: CHEM Primary 1 2014-12-04.
info:    Completed queueing.
```

**Comment by jerowe** [comment]
@twaddlac , you're right the script was renamed.

Instead of running the screen imports in real time jobs/processScreens (and everything in the 'jobs') folder instead hands them off to a job queing system called bull. 

https://github.com/OptimalBits/bull

I have a minimal bull example https://github.com/jerowe/node-bull-example if you're interested, but its not much different than whats in the jobs folder.

These jobs are meant to run in the background just check the pm2 logs with `pm2 logs chemgen-next-define-queues`. If you want to force it to log to your current terminal just increase the limit to some number greater than 1. I'm not totally sure why this is, if its a bug in bull or has something to do with the logging priority or what.

FYI - ignore most scripts in the 'bin' directory. It is basically a one off use scratch directory. 

Thanks for the updates to the readme!

**Comment by jerowe** [comment]
So I've confirmed that the jobs don't start unless you queue up more than 1, which is pretty undesirable behavior. I'll investigate what is happening there. For now just force it with `limit >1`
